# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: 'Chuckya'
  site_short_description: ''
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'none'
  profile_directory: true
  closed_registrations_message: ''
  local_live_feed_access: 'authenticated'
  bubble_live_feed_access: 'authenticated'
  remote_live_feed_access: 'authenticated'
  local_topic_feed_access: 'authenticated'
  bubble_topic_feed_access: 'authenticated'
  remote_topic_feed_access: 'authenticated'
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: false
  flavour: 'glitch'
  skin: 'system'
  trends: true
  trendable_by_default: true
  trending_status_cw: true
  visible_reactions: 6
  hide_followers_count: false
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_reblogs_in_public_timelines: true
  show_replies_in_public_timelines: true
  default_content_type: 'text/markdown'
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  show_bubble_domains: 'users'
  outgoing_spoilers: ''
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: false
  reject_pattern: ''
  reject_blurhash: ''
  allow_referrer_origin: false
  landing_page: 'trends'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
